F:\toolkithelper.exe C:\MOUNT GameExplorer
F:\toolkithelper.exe C:\MOUNT SnippingTool
F:\toolkithelper.exe C:\MOUNT SpeechRecognition
F:\toolkithelper.exe C:\MOUNT WindowsMediaPlayer
F:\toolkithelper.exe C:\MOUNT WinSAT
F:\toolkithelper.exe C:\MOUNT AssignedAccess
F:\toolkithelper.exe C:\MOUNT CEIP_SQM
F:\toolkithelper.exe C:\MOUNT KernelDebugging
F:\toolkithelper.exe C:\MOUNT LocationService
F:\toolkithelper.exe C:\MOUNT UnifiedTelemetryClient
F:\toolkithelper.exe C:\MOUNT WindowsErrorReporting
F:\toolkithelper.exe C:\MOUNT WindowsInsiderHub
F:\toolkithelper.exe C:\MOUNT HomeGroup
F:\toolkithelper.exe C:\MOUNT MultiPointConnector
F:\toolkithelper.exe C:\MOUNT RemoteAssistance
F:\toolkithelper.exe C:\MOUNT DeviceLockdown
F:\toolkithelper.exe C:\MOUNT EaseOfAccessThemes
F:\toolkithelper.exe C:\MOUNT Paint
F:\toolkithelper.exe C:\MOUNT SecurityCenter
F:\toolkithelper.exe C:\MOUNT SystemRestore
F:\toolkithelper.exe C:\MOUNT WindowsToGo
F:\toolkithelper.exe C:\MOUNT AADBrokerPlugin
F:\toolkithelper.exe C:\MOUNT AssignedAccessLockApp
F:\toolkithelper.exe C:\MOUNT CBSPreview
F:\toolkithelper.exe C:\MOUNT ContentDeliveryManager
F:\toolkithelper.exe C:\MOUNT Cortana
F:\toolkithelper.exe C:\MOUNT ECApp
F:\toolkithelper.exe C:\MOUNT EdgeDevToolsClient
F:\toolkithelper.exe C:\MOUNT Edge
F:\toolkithelper.exe C:\MOUNT MapControl
F:\toolkithelper.exe C:\MOUNT OneDrive
F:\toolkithelper.exe C:\MOUNT NarratorQuickStart
F:\toolkithelper.exe C:\MOUNT ParentalControls
F:\toolkithelper.exe C:\MOUNT PeopleExperienceHost
F:\toolkithelper.exe C:\MOUNT PPIProjection
F:\toolkithelper.exe C:\MOUNT QuickAssist
F:\toolkithelper.exe C:\MOUNT RetailDemoContent
F:\toolkithelper.exe C:\MOUNT SecureAssessmentBrowser
F:\toolkithelper.exe C:\MOUNT SettingSync
F:\toolkithelper.exe C:\MOUNT SkypeORTC
F:\toolkithelper.exe C:\MOUNT SmartScreen
F:\toolkithelper.exe C:\MOUNT WindowsDefender
F:\toolkithelper.exe C:\MOUNT WindowsMixedReality
F:\toolkithelper.exe C:\MOUNT WindowsReaderPDF
F:\toolkithelper.exe C:\MOUNT XboxGameCallableUI
F:\toolkithelper.exe C:\MOUNT 3DViewer
F:\toolkithelper.exe C:\MOUNT AdvertisingXaml
F:\toolkithelper.exe C:\MOUNT Alarms
F:\toolkithelper.exe C:\MOUNT BingWeather
F:\toolkithelper.exe C:\MOUNT Calculator
F:\toolkithelper.exe C:\MOUNT CommunicationsApps
F:\toolkithelper.exe C:\MOUNT FeedbackHub
F:\toolkithelper.exe C:\MOUNT GetHelp
F:\toolkithelper.exe C:\MOUNT Getstarted
F:\toolkithelper.exe C:\MOUNT Maps
F:\toolkithelper.exe C:\MOUNT Messaging
F:\toolkithelper.exe C:\MOUNT MixedRealityPortal
F:\toolkithelper.exe C:\MOUNT OfficeHub
F:\toolkithelper.exe C:\MOUNT OfficeOneNote
F:\toolkithelper.exe C:\MOUNT OneConnect
F:\toolkithelper.exe C:\MOUNT Paint3D
F:\toolkithelper.exe C:\MOUNT People
F:\toolkithelper.exe C:\MOUNT Photos
F:\toolkithelper.exe C:\MOUNT Print3D
F:\toolkithelper.exe C:\MOUNT ScreenSketch
F:\toolkithelper.exe C:\MOUNT SkypeApp
F:\toolkithelper.exe C:\MOUNT SolitaireCollection
F:\toolkithelper.exe C:\MOUNT SoundRecorder
F:\toolkithelper.exe C:\MOUNT StickyNotes
F:\toolkithelper.exe C:\MOUNT WalletService
F:\toolkithelper.exe C:\MOUNT XboxApp
F:\toolkithelper.exe C:\MOUNT XboxIdentityProvider
F:\toolkithelper.exe C:\MOUNT YourPhone
F:\toolkithelper.exe C:\MOUNT ZuneMusic
F:\toolkithelper.exe C:\MOUNT ZuneVideo